DROP TABLE IF EXISTS FILES;

CREATE TABLE FILES COMMENT '파일' (
  FILE_ID VARCHAR(50) NOT NULL COMMENT '파일아이디',
  FILE_NO NUMERIC NOT NULL COMMENT '파일번호',
  FILE_GRP_ID VARCHAR(50) NOT NULL COMMENT '파일그룹아이디',
  FILE_NM VARCHAR(500) NOT NULL COMMENT '파일명',
  ORG_FILE_NM VARCHAR(500) NOT NULL COMMENT '원본파일명',
  FILE_FMT_CONT VARCHAR(500) COMMENT '파일형식',
  SV_PATH VARCHAR(500) COMMENT '저장경로',
  FILE_SZ NUMERIC NOT NULL COMMENT '파일사이즈',
  PRIMARY KEY (FILE_ID, FILE_NO)
);